### ISSUE TITLE
changing filament

### ISSUE THREAD

**Issue by Romarioo7** [ThomasToka/MarlinFirmware#36]
Hello my friend! thanks for the firmware. I can't seem to print with changing colors in the slicer. Tell me how to properly configure the slicer to pause and replace the filament. Thank you in advance!

**Comment by ThomasToka** [comment]
Hello,
this is a "issue" reporting system for reporting problems with the firmware.

This a not a support channel for basic printing/feature questions.

Please use the channels on the discord for such questions.

To you question:

a) you can use M600 filament change:

![grafik](https://github.com/ThomasToka/MarlinFirmware/assets/117008525/8ceaf278-05b6-4eb4-b7af-5f2ec90e19b1)

b) you can use M0 "pause at height"

https://github.com/ThomasToka/MarlinFirmware/wiki/Pause-at-height-(M0)

**Comment by ar360yandexru** [comment]
Good afternoon, can you  add the option to change the filament next to the pause button.
For example, I paused -> pressed the "change filament" button-> drove off to the XY parking place -> replaced the filament -> squeezed out 100mm of filament so that the replacement took place -> removed it carefully with my hand -> pressed the button -> continued printing.

Also, this algorithm can be applied as soon as the filament motion sensor is triggered

Thank you very much from Russia, Samara.
